### ISSUE TITLE
Redirect to https://dataset.api.hub.geosphere.at goes into action soon

### ISSUE THREAD

**Issue by afuchs-geosphereat** [Geosphere-Austria/dataset-api-docs#13]
## Description

The previously announced redirect from https://dataset.api.hub.zamg.ac.at/ to https://dataset.api.hub.geosphere.at/ will be activated soon. 

Requests sent to https://dataset.api.hub.zamg.ac.at should follow redirects or better should be sent to https://dataset.api.hub.geosphere.at/ directly.

**Comment by dlang-geosphereat** [comment]
As of today this is now active. See https://dataset.api.hub.geosphere.at/v1/docs/changelog.html#changelog-20230918
