### ISSUE TITLE
geosphere API: station_id

### ISSUE THREAD

**Issue by remotelink** [Geosphere-Austria/dataset-api-docs#17]
für ein kleines privates projekt würde ich gerne über die API an mess-stations-daten (in meinem fall: luftdruck) kommen. typischerweise messe ich das selbst, aber meine messtelle fällt immer wieder aus, wenn lange keine sonne scheint. dafür hätte ich gerne ein backup ... 

irgendwie komme ich mit dem gezeigten beispiel der abfrage API:
[https://dataset.api.hub.geosphere.at/v1/docs/getting-started.html#example](https://dataset.api.hub.geosphere.at/v1/docs/getting-started.html#example)
nicht klar. 

der aufbau ist verständlich, aber ich fand nirgendwo eine beschreibung oder die information für die möglichen mess-"parameter" und die liste der möglichen messstationen und ihrer: "station_id"

z.b von der station: "bregenz" den "lokalen luftdruck" für den API-request:

https://dataset.api.hub.geosphere.at/v1/station/current/tawes-v1-10min?parameters=CODEFÜRLUFTDRUCK&station_ids=FÜRBREGENZ](https://dataset.api.hub.geosphere.at/v1/station/current/tawes-v1-10min?parameters=CODEF%C3%9CRLUFTDRUCK&station_ids=F%C3%9CRBREGENZ)

wo finde ich diese informationen?

**Comment by dlang-geosphereat** [comment]
Danke für das Feedback. Jeder Datensatz hat einen `/metadata` Endpoint der diese Informationen auflistet, in diesem Fall https://dataset.api.hub.geosphere.at/v1/station/current/tawes-v1-10min/metadata

Dort sind sowohl Parameter- als auch Stationsinformationen aufgelistet.

**Comment by remotelink** [comment]
so einfach wäre es gegangen. vielen dank, für die hilfe

`$ curl --silent "https://dataset.api.hub.geosphere.at/v1/station/current/tawes-v1-10min?parameters=P&station_ids=11105" | jq
{
  "media_type": "application/json",
  "type": "FeatureCollection",
  "version": "v1",
  "timestamps": [
    "2023-11-21T08:30+00:00"
  ],
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          9.609722222222222,
          47.27111111111111
        ]
      },
      "properties": {
        "parameters": {
          "P": {
            "name": "Luftdruck",
            "unit": "hPa",
            "data": [
              962.1
            ]
          }
        },
        "station": "11105"
      }
    }
  ]
}
`
