### ISSUE TITLE
No up-to-date data from TAWES endpoint / delay

### ISSUE THREAD

**Issue by HenrikLe** [Geosphere-Austria/dataset-api-docs#18]
Dear contributors,

We are currently experiencing issues with receiving up-to-date data from the TAWES endpoint.

For instance, when accessing the URL https://dataset.api.hub.geosphere.at/v1/station/current/tawes-v1-10min?parameters=TL&station_ids=11266, we observe that it only provides data from yesterday. The same issue persists with the "historical" endpoint.

We are curious whether this is due to an issue on our side or if there is a server outage. Alternatively, could you confirm in what interval the data is intended to be updated?

Your assistance in clarifying this matter would be greatly appreciated.

Thank you and best regards!

**Comment by dlang-geosphereat** [comment]
Hi @HenrikLe 
sorry, for this interruption of service. There was an issue with our internal data source. This problem was fixed on Friday afternoon/evening and new data should be available again. 

If you still experience problems, please feel free to re-open this issue.
