### ISSUE TITLE
Document bounding box format in text

### ISSUE THREAD

**Issue by dlang-geosphereat** [Geosphere-Austria/dataset-api-docs#19]
## Description

We received internal feedback, that the bbox format is not documented in the text: https://dataset.api.hub-staging.geosphere.at/v1/docs/user-guide/type.html#term-bbox

It **is** documented in the OpenAPI (https://dataset.api.hub.geosphere.at/v1/openapi-docs#/grid/Historical_Grid_Data_grid_historical__resource_id__get), but we do not link there and I agree with the feedback, that this information should be easier to find. 

I propose we either also have this information directly in the description text or link to the specific portion in the OpenAPI Docs .

**Comment by afuchs-geosphereat** [comment]
Closed by #22
