### ISSUE TITLE
station/historical ... parameters don't work as documented

### ISSUE THREAD

**Issue by nitmws** [Geosphere-Austria/dataset-api-docs#24]
I want to request historical weather data of a station. Looking at the API documentation I see at https://dataset.api.hub.geosphere.at/v1/openapi-docs#/station/Historical_Station_Data_station_historical__resource_id__get  that the types of measured data required the query parameter "parameters" taking an array of strings as value. The same applies to the query parameter "station_ids"
Addressing the data of the station Wien-Hohe Warte (id "105") I created this URL as advised in the documentation:
https://dataset.api.hub.geosphere.at/v1/station/historical/klima-v1-1d?parameters=["t","tmin","tmax"]&start=2022-01-01&end=2022-12-31&station_ids=["105"]&output_format=geojson
Hm, " are not allowed in URLs, so I encoded it to
https://dataset.api.hub.geosphere.at/v1/station/historical/klima-v1-1d?parameters=[%22t%22,%22tmin%22,%22tmax%22]&start=2022-01-01&end=2022-12-31&station_ids=[%22105%22]&output_format=geojson

... but both URL returned this response:
{"detail":"Parameters {'\"tmin\"', '[\"t\"', '\"tmax\"]'} do not exist or access is denied"}

Finally I tried it with a version of parameter setting I used for the ZAMG API: parameters=t&parameters=tmin&parameters=tmax ... and this worked for parameters, now this is returned:
{"detail":"Station ids {'[\"105\"]'} are not allowed"}

My summary: using Javascript-like arrays in query parameters doesn't work. 
Please:
* change the syntax of the array to e.g. parameter=t,tmin,tmax and station_ids=105,100,4125 (= a string of values separated by comma)
* correct the FastAPI documentation to that syntax
* OR don't change the syntax but adjust the FastAPI documentation to it

**Comment by dlang-geosphereat** [comment]
Hi @nitmws ,

thank you for your feedback. We currently support two formats for `station_ids` and `parameters`:
* a string with comma `,` as a delimiter, e.g. `?parameters=t,tmin,tmax` or
* via multiple parameters, e.g. `?parameters=t&parameters=tmin&parameters=tmax`

Note that "array" does not necessarily mean `[` and `]`. This is framework specific and unfortunately there is no framework-agnostic way of passing array values in a query string. In FastAPI passing an array simply means listing the GET-parameter multiple times (see option 2).

> Finally I tried it with a version of parameter setting I used for the ZAMG API: parameters=t&parameters=tmin&parameters=tmax ... and this worked for parameters, now this is returned:
{"detail":"Station ids {'["105"]'} are not allowed"}

This is correct, and as the error indicates is not a problem with the parameters. However, you did not change the syntax for `station_ids`.

Your URL should look like this: https://dataset.api.hub.geosphere.at/v1/station/historical/klima-v1-1d?parameters=t,tmin,tmax&start=2022-01-01&end=2022-12-31&station_ids=105&output_format=geojson

If you need multiple stations, you can simply add them after `105` and separate with commas (see option 1). Hope this helps.

**Comment by dlang-geosphereat** [comment]
The OpenAPI docs at https://dataset.api.hub.geosphere.at/v1/openapi-docs#/station/Historical_Station_Data_station_historical__resource_id__get are just a visualization of the [openapi.json](https://dataset.api.hub.geosphere.at/v1/openapi.json). The specified `type` and `example` only show the semantics of parameters, not how to transfer them. The "Try it out" button allows you to test the examples and also try your own queries. You can add additional parameters using the button "Add a string item" (since it is an array of strings) and it will automatically create a valid query URL.

That being said, I can see, that we do not handle this scenario well in the documentation and we'll add more information about handling array types. Thanks again for bringing this to our attention.

**Comment by nitmws** [comment]
Ah, now I recall how I got to use multiple parameter=... parameters with the API: it was based on "Try it out" - but I did that long time ago.

I'm looking forward to a generic explanation in the native Geosphere documentation as this avoids having to go the trial and error track.
