### ISSUE TITLE
Max number of requests

### ISSUE THREAD

**Issue by AlexPucher** [Geosphere-Austria/dataset-api-docs#28]
Hello,

is there a maximum number of requests on the Geosphere API?

Sorry if I missed this information in the docs!

Best, Alex.

**Comment by dlang-geosphereat** [comment]
Hi Alex,

looks like **we** missed this in the docs. Yes, we do have rate-limiting for data endpoints. We set corresponding headers for this information. See the following example:
```
$ curl --head -X GET https://dataset.api.hub.geosphere.at/v1/station/current/tawes-v1-10min/metadata                                                    
HTTP/2 200 
content-type: application/json
content-length: 86985
ratelimit-reset: 1
ratelimit-remaining: 4
x-ratelimit-remaining-second: 4
x-ratelimit-limit-second: 5
x-ratelimit-remaining-hour: 232
x-ratelimit-limit-hour: 240
date: Wed, 06 Mar 2024 14:34:36 GMT
...
```

There are multiple limits in place:
1. 5 requests per second (`x-ratelimit-limit-second`)
2. 240 requests per hour ( `x-ratelimit-limit-hour`)

the `*-remaining`  fields indicate how many requests are left for that window.

These values have been chosen to enable "typical" requests. If you have a use case, where you need to do more requests, we'd love to hear it.

Best,
Daniel
