### ISSUE TITLE
Tawes-API frozen

### ISSUE THREAD

**Issue by moberhofer** [Geosphere-Austria/dataset-api-docs#33]
Since yesterday the retrieval of current weather data via the tawes-API always returns the value of 2024-05-12T09:50+00:00, no matter which station is selected.
e.g. https://dataset.api.hub.geosphere.at/v1/station/current/tawes-v1-10min?parameters=TL,GLOW&station_ids=11227

Are you already aware of the problem? Or are you already working on a solution?

Thank you very much, best regards,
Michael Oberhofer

**Comment by dlang-geosphereat** [comment]
Hi @moberhofer, thank you for letting us know about this issue. I've forwarded this issue internally to our data providers and hope it can be resolved soon.

**Comment by moberhofer** [comment]
Thanks for working on the issue. It is fixed for now.

**Comment by moberhofer** [comment]
Since 14:20, the API is again frozen and delivers only the same values.

**Comment by mranner** [comment]
tawes-v1-10 no longer updated since 15:40, no mention about changes with klima-v2 changelog, crurent endpoints do not accept other resource ids

**Comment by moberhofer** [comment]
How do I migrate to klima-v2 to archieve the same result as before? All examples in the docs uses the v1.

**Comment by dlang-geosphereat** [comment]
Thank you for the report, I relayed this information to the data producers.

@mranner Feel free to create a separate issues for other problems you are experiencing. As from what I've understand:

> no mention about changes with klima-v2 changelog

Please clarify what kind of information your are missing. The deprecation notice for klima-v1 datasets came together with the release of the klima-v2 datasets.

>  current endpoints do not accept other resource ids

This is on purpose. The issue here is, that often a manual process for data correction follows, which means there is no way of knowing what "current" actually means in this context. Please create an issue and describe your use case and how we could make this a better experience.

**Comment by mranner** [comment]
@dlang-geosphereat, there is no replacement for tawes-v1-10 in the docs, the klima-v2 dataset do not work with the /v1/station/current/ endpoint. There is no documentation how to update tawes-v1-10 to something other.

`https://dataset.api.hub.geosphere.at/v1/station/current/tawes-v1-10min?parameters=P%2CRF%2CTL&station_ids=11238&output_format=csv`

will always deliver this result

`2024-09-02T12:40+00:00,11238,972.7,35.0,30.6`

So it seems related to the klima-v1 to klima-v2 change, but there is no alternative resource_id for /v1/station/current/...

**Comment by dlang-geosphereat** [comment]
> How do I migrate to klima-v2 to archieve the same result as before?

The only thing that **needs** to change are parameter names. We provide information about the mapping for old (v1) parameter names to the new ones (v2): https://dataset.api.hub.geosphere.at/v1/docs/changelog.html#backwards-incompatible-changes

> All examples in the docs uses the v1.

This is certainly an oversight and we'll fix that.

**Comment by dlang-geosphereat** [comment]
@mranner I understand it now. There is currently no successor for `tawes-v1`. The endpoint **/station/current/tawes-v1-10min is not affected by the scheduled change**. Data not being available there is an operational problem, that has nothing to do with the scheduled deprecation of the following 4 datasets:
* `klima-v1-10min`
* `klima-v1-1h`
* `klima-v1-1d`
* `klima-v1-1m`

It's an unfortunate coincidence this happened on the same day.

**Comment by mranner** [comment]
@dlang-geosphereat correct, but tawes-v1 is stuck to old data since the change, so it seems to be affected from the klima-v1 deprecation, because there is no new data.

**Comment by moberhofer** [comment]
@dlang-geosphereat 
That clears things up. I hope the tawes-v1 is working soon again, many services uses this source for gathering actual data.

**Comment by moberhofer** [comment]
@dlang-geosphereat Do you have any updates on the tawes-v1 datasource? It still does not deliver actual data.

**Comment by mranner** [comment]
@dlang-geosphereat at the moment the result is

```
{
  "details": "Database is currently not available. Try again later!"
}
```
