### ISSUE TITLE
AROME FTP Server still working under same address?

### ISSUE THREAD

**Issue by RobinKohrs** [Geosphere-Austria/dataset-api-docs#34]
Hi all:)
Maybe I'm just missing something very obvious. But I tried to throw the 

ftp://eaftp.zamg.ac.at/nwp (as listed [here](https://data.hub.geosphere.at/dataset/nwp-v1-1h-2500m))

into my filezilla and it says: "No route to host". Am I missing something or did the endpoint maybe move somewhere else?

Thanks a lot!:) Best, Robin

**Comment by dlang-geosphereat** [comment]
Hi Robin,

no you are not missing anything. "No route to host" usually indicates some kind of network problem, either on our side, on your side or anywhere inbetween.

I cannot reproduce this and the host is reachable for me now. I do not have uptime information for the FTP servers at hand. I suggest you try again now.

Best,
Daniel

**Comment by RobinKohrs** [comment]
Hi Daniel,
thanks so much for the quick reply and the help! Seems to be up and running again:))
