### ISSUE TITLE
Timezone of Arome netCDF

### ISSUE THREAD

**Issue by RobinKohrs** [Geosphere-Austria/dataset-api-docs#35]
Hi All,
I am really sorry for this basic question. Probably there is a convention for the timestamps in a netCDF-file. But just to be absolutely sure and dont mix things up. Are the time-values in the arome-products in UTC?
Thanks so much, Robin

**Comment by dlang-geosphereat** [comment]
Hi Robin!

Yes, they are in UTC. Generally we try to provide timezone information, if no timezone information is present, it's usually UTC. But if you are unsure, don't hesitate to ask.

Moreover, we are (mostly) compliant to the CF conventions: https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch04s04.html which says:

>  Note: if the time zone is omitted the default is UTC, and if both time and time zone are omitted the default is 00:00:00 UTC. 

Hope this helps!

**Comment by RobinKohrs** [comment]
Great!:) Thanks so much:)
