### ISSUE TITLE
Sunshine duration not available for StationID 30?

### ISSUE THREAD

**Issue by michelesalmi** [Geosphere-Austria/dataset-api-docs#40]
Hi all,

I have just noticed that recent sunshine duration data are not available at the climate station ID 30 (Graz Universität), at least for the daily timeserie. Is this correct or should the new location of the weather station report sunshine duration as well?

Thank you,
Michele

**Comment by michelesalmi** [comment]
Sorry I just noticed that also the wind speed (at least the wind gusts) is affected at ID 30.

**Comment by dlang-geosphereat** [comment]
> Is this correct or should the new location of the weather station report sunshine duration as well?

Yes, this is correct. You can check this by looking for the `has_sunshine` attribute in the metadata of `stations`  or in the frontend:
![image](https://github.com/user-attachments/assets/03ee1637-1725-42f5-a22b-1b8757b6301f)

>  I just noticed that also the wind speed (at least the wind gusts) is affected at ID 30.

This is also correct. The station does not provide wind measurements. We are working on an updated version, that will provide more metadata about which parameter information is available. Unfortunately, this is a breaking change to the current API version and will need some time.

Btw. Station 30 is a _station series_, which means that you can query it like a regular station, but the data is provided by multiple stations, that may provide different parameters.
