### ISSUE TITLE
/v1/station/current/tawes-v1-10min/metadata Weiz Teststation hat verdrehte Koordinaten

### ISSUE THREAD

**Issue by PhilippKolmann** [Geosphere-Austria/dataset-api-docs#41]
Ich bin gerade dabei die öffentlichen Daten für ein Forschungsprojekt zuverstehen und habe dazu eine Visualisierung der Stations vom API Endpoint https://dataset.api.hub.geosphere.at/v1/station/current/tawes-v1-10min/metadata gemacht...

Hierbei ist mir aufgefallen, das die Station "WEIZ - TESTSTATION / Steiermark" etwas abseits der Steiermark liegt:

![image](https://github.com/user-attachments/assets/a0e13380-08af-461c-9cd0-e6aa34f027be)

Könnt ihr bitte die Koordinaten hier richtigstellen, oder ist das absicht, weil es eine Teststation ist?

danke,
lg
Philipp

**Comment by dlang-geosphereat** [comment]
Hallo Philipp,

danke für den Hinweis. Ich habe das Problem an die weitergegeben und melde mich nochmal, sobald die Änderung durchgeführt wurde.
